Make Mypy happy
We're assigning to an attribute Mypy doesn't know about. The error it
raised:

    injector/__init__.py:862: error: "FunctionType" has no attribute "__binding__"  [attr-defined]
    Found 1 error in 1 file (checked 1 source file)