Fix new issues discovered by latest mypy (0.750)
The errors in question:

    % mypy injector
    injector/__init__.py:34: error: Incompatible types in assignment (expression has type "None", variable has type "_SpecialForm")
    injector/__init__.py:37: error: All conditional function variants must have identical signatures
    injector/__init__.py:1067: error: Argument 1 to "pop" of "MutableMapping" has incompatible type "Optional[str]"; expected "str"
    injector/__init__.py:1068: error: Argument 1 to "pop" of "MutableMapping" has incompatible type "Optional[str]"; expected "str"

Coincidentally this commit fixes an issue [1] discovered by eugenhu.
Although the solution to the issue is different than eugenhu suggests
the analysis of the underlying cause is helpful and appreciated.

[1] "Cannot inject dependency which is a subclass of a subscripted type", GH-128

Closes GH-128