Create a dedicated constructor for BindingKey
With the old code mypy would complain about the constructor being called
incorrectly:

    injector.py:717: error: Argument 1 to "BindingKey" has incompatible type "T"; expected "Iterable[Any]"