Support NewType
Previously it would fail with:

    Traceback (most recent call last):
      File "/Users/kuba/projects/injector/injector_test.py", line 1339, in test_newtype_integration_works
        injector = Injector([configure])
      File "/Users/kuba/projects/injector/injector.py", line 667, in __init__
        self.binder.install(module)
      File "/Users/kuba/projects/injector/injector.py", line 389, in install
        args=(self,),
      File "/Users/kuba/projects/injector/injector.py", line 856, in call_with_injection
        reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
      File "/Users/kuba/projects/injector/injector.py", line 65, in reraise
        raise exception.with_traceback(tb)
      File "/Users/kuba/projects/injector/injector.py", line 854, in call_with_injection
        **dependencies)
      File "/Users/kuba/projects/injector/injector_test.py", line 1337, in configure
        binder.bind(UserID, to=123)
      File "/Users/kuba/projects/injector/injector.py", line 292, in bind
        self.create_binding(interface, to, scope)
      File "/Users/kuba/projects/injector/injector.py", line 393, in create_binding
        provider = self.provider_for(interface, to)
      File "/Users/kuba/projects/injector/injector.py", line 439, in provider_for
        raise TypeError('Injecting partially applied functions is no longer supported.')
    TypeError: Injecting partially applied functions is no longer supported.