Remove support for injecting partially applied functions
This feature doesn't cooperate nicely with Python 3-style
annotation-based injection and mypy, I don't think it's worth keeping it.

Let's have code like this:

    def function(s: str) -> str:
        return s

    class X:
        def __init__(self, f: function) -> None:
            print(f())

It will work at runtime (Injector-specific boilerplate missing from this
sample) but mypy will complain:

    t.py: note: In function "__init__":
    t.py:6: error: Invalid type "t.function"
    t.py: note: In member "__init__" of class "X":
    t.py:7: error: object not callable